### PR TITLE
Fix `fromListWithDef` divergence

### LINKED ISSUE #39: `fromListWithDef` diverges
The following example diverges, with ghc-9.8.2 and ghc-9.6.4

```haskell
naturals :: UChimera Int
naturals = fromListWithDef 0 [0..]

main :: IO ()
main = print (index naturals 0)
```

If you can reproduce @Bodigrim, I can investigate and prepare a PR.

### PR DESCRIPTION
**Pull request by pgujjula**
`fromListWithDef` diverges when passed an infinite list, for the following reasons:

**Reason 1:**

* `fromListWithDef` calls `Data.Primitive.Array.fromListN (bits + 1)`. `fromListN` requires that the length of the list that is passed to it is exactly `bits + 1`. To ensure this, it forces the spine of the list that is passed to it.
* The list that is passed to `fromListN` is generated by `go0`, which calls `go`. When `xs` is infinite, `go k xs` will be infinite. Therefore, `fromListN` will throw an error since `go0` yields a list longer than `bits + 1`.

Even if we take the first `bits + 1` elements of `go0` before passing to `fromListN`, there is another problem. 

**Reason 2:**

* As `fromListN` forces the spine, it will compute `go 0 xs0`, `go 1 xs1`, ..., `go 63 xs63`, for some `xs0`, `xs1`, ..., `xs63`.

* This in turn requires computing `measureOff (2^0) xs0`, `measureOff (2^1) x1`, ..., `measureOff (2^63) x63`, which is essentially divergent.

~~To avoid these problems, we implement `fromListWithDef` in terms of `fromInfinite`. Note that the implementation of `fromInfinite` is similar to the old implementation of `fromListWithDef`, except that it doesn't call `measureOff`, which is the source of the divergence.~~

**Updated solution:** To avoid these problems, we

* Add a check in `go` to break recursion and ensure that the list that is passed to `fromListN` has length `bits + 1`.

* Rearrange how we compute `go`, so that `measureOff` is not forced while forcing the spine of `go`.

---

This PR depends on PR https://github.com/Bodigrim/chimera/pull/41, which should be merged first.

Fixes issue https://github.com/Bodigrim/chimera/issues/39

### CODE REVIEW

**Comment by Bodigrim** [comment]
I'm not quite sure about this approach. The existing implementation is better for finite lists, because `G.replicate` is very efficient, much faster than iterating `Inf.repeat a :: Infinite a`. 

Could it be possible to rewrite `go` to be lazier, not forcing `measureOff` prematurely? After all, both branches in `go` return `(:)`...

**Comment by pgujjula** [comment]
> Could it be possible to rewrite go to be lazier, not forcing `measureOff` prematurely? After all, both branches in `go` return `(:)`...

Sounds good, it will take me a little while to figure out. I'll try to finish it by the end of the day.

**Comment by pgujjula** [comment]
@Bodigrim I've updated the PR accordingly.

**Comment by pgujjula** [comment]
@Bodigrim Ok, it's ready now!

File: src/Data/Chimera/Internal.hs [hunk 1]
```diff
@@ -553,13 +553,19 @@ fromListWithDef a = Chimera . fromListN (bits + 1) . go0
...
+        then []
+        else v : go (k + 1) zs
       where
         kk = 1 `shiftL` k
+        (v, zs) =
+          case measureOff kk xs of
+            Left l ->
+              if l == kk
+                then (G.replicate kk a, [])
+                else (G.fromListN kk (xs ++ replicate l a), [])
```
Comment (Bodigrim) [inline src/Data/Chimera/Internal.hs:567]: I'd probably write it as `(if l == kk then ... else ..., [])`, but up to you.

**Review by Bodigrim — COMMENTED** [review]
Looks good, could you please add a test?

File: src/Data/Chimera/Internal.hs (hunk 1 above)
Comment (pgujjula) [reply src/Data/Chimera/Internal.hs]: Ok, I rewrote it that way

**Comment by pgujjula** [comment]
I added a test for infinite inputs to `fromListWithDef`

**Review by Bodigrim — APPROVED** [review]

**Comment by Bodigrim** [comment]
Thanks a ton!

**Comment by Bodigrim** [comment]
Released in https://hackage.haskell.org/package/chimera-0.4.1.0
